# Generated by Django 5.1.3 on 2024-12-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_remove_file_target_update_remove_file_update_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
