# Generated by Django 5.1.3 on 2024-12-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionupdate',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILED'), (3, 'IN_PROGRESS')], default=4),
        ),
    ]
