# Generated by Django 5.1.3 on 2024-12-04 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_update_name_alter_versionupdate_status'),
        ('version', '0002_version_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionupdate',
            name='version',
        ),
        migrations.AddField(
            model_name='update',
            name='all_devices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='update',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version.version'),
        ),
    ]
