# Generated by Django 5.1.3 on 2024-12-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('update', '0004_remove_versionupdate_version_update_all_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionupdate',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device'),
        ),
        migrations.AlterField(
            model_name='versionupdate',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='update.update'),
        ),
    ]
