# Generated by Django 5.1.3 on 2024-12-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_alter_versionupdate_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='versions',
            new_name='devices',
        ),
    ]
